(.venv) (base) mahdi@s-8d3a265e testing-python-exercise-wt2425 % pytest -s
==================================== test session starts =====================================
platform darwin -- Python 3.12.4, pytest-7.4.4, pluggy-1.0.0
rootdir: /Users/mahdi/Documents/SSE Exercises/testing-python-exercise-wt2425
plugins: anyio-4.2.0
collected 8 items                                                                            

tests/integration/test_diffusion2d.py ..
tests/unit/test_diffusion2d_functions.py .dt = 2.0000000000000012e-05
F..dt = 2.0000000000000012e-05
F.

========================================== FAILURES ==========================================
____________________________ test_initialize_physical_parameters _____________________________

    def test_initialize_physical_parameters():
        """
        Checks function SolveDiffusion2D.initialize_domain
        """
        solver = SolveDiffusion2D()
    
        _d = 5.
        _T_cold = 500.
        _T_hot = 600.
    
        solver.dx = 0.1
        solver.dy = 0.1
    
        solver.initialize_physical_parameters(d=_d, T_cold=_T_cold, T_hot=_T_hot)
    
>       assert solver.dt == 0.0005000000000000001
E       assert 2.0000000000000012e-05 == 0.0005000000000000001
E        +  where 2.0000000000000012e-05 = <diffusion2d.SolveDiffusion2D object at 0x114d217c0>.dt

tests/unit/test_diffusion2d_functions.py:42: AssertionError
____________________ TestDiffusion2D.test_initialize_physical_parameters _____________________

self = <tests.unit.test_diffusion2d_functions.TestDiffusion2D testMethod=test_initialize_physical_parameters>

    def test_initialize_physical_parameters(self):
        """
        Checks function SolveDiffusion2D.initialize_domain
        """
        solver = SolveDiffusion2D()
    
        _d = 5.
        _T_cold = 500.
        _T_hot = 600.
    
        solver.dx = 0.1
        solver.dy = 0.1
    
        solver.initialize_physical_parameters(d=_d, T_cold=_T_cold, T_hot=_T_hot)
    
>       self.assertAlmostEqual(solver.dt,0.0005,delta=0.0000001,msg='dt not correct')
E       AssertionError: 2.0000000000000012e-05 != 0.0005 within 1e-07 delta (0.00048 difference) : dt not correct

tests/unit/test_diffusion2d_functions.py:94: AssertionError
================================== short test summary info ===================================
FAILED tests/unit/test_diffusion2d_functions.py::test_initialize_physical_parameters - assert 2.0000000000000012e-05 == 0.0005000000000000001
FAILED tests/unit/test_diffusion2d_functions.py::TestDiffusion2D::test_initialize_physical_parameters - AssertionError: 2.0000000000000012e-05 != 0.0005 within 1e-07 delta (0.00048 difference) ...
================================ 2 failed, 6 passed in 0.26s =================================
(.venv) (base) mahdi@s-8d3a265e testing-python-exercise-wt2425 % 